### PR TITLE
Remove old menu, add links to new menu, fix avatar

### PR DESCRIPTION
**Pull request by NicholasAntonov**

### CODE REVIEW

**Comment by eshellman** [comment]
don't you think clicking the avatar should do something?

**Comment by eshellman** [comment]
Profile settings link doesn't go to profile settings.

**Comment by eshellman** [comment]
the notification number badge (green dot) has turned into a duplicate menu item

**Comment by eshellman** [comment]
is this the right place to note that the "learn more" button should be turned into a link?

**Comment by NicholasAntonov** [comment]
Which learn more button? Could you provide a screenshot or a URL?

**Comment by eshellman** [comment]
image

**Comment by eshellman** [comment]
running on m.unglue.it

**Pull request merged**
