### PR TITLE
fix home css / add explore section to book view sidebar

### PR DESCRIPTION
**Pull request by JonahMania**

### CODE REVIEW

**Comment by eshellman** [comment]
side bar works.

This is probably my fault for communicating badly, but we need to have the content of the ungluers tab back (we removed the ungluers secton of "explore". Very important for books that have been crowdfunded - we need to show the supporters. (perhaps for purposes of the course submission better to leave it as an issue)

**Comment by eshellman** [comment]
also, the book page has a donate button that shouldn't always be there

**Comment by JonahMania** [comment]
@eshellman what is the condition to have the donate button on the page?

**Comment by eshellman** [comment]
the logic for the button is in templates/work_action.html:

```
<div class="clearfix">
    {% if status == 'ACTIVE' %}
      {% if work.last_campaign.type == 1 %}
        {% if pledged %}
            <div class="btn_support modify"><form action="{% url 'pledge_modify' work_id %}" method="get"><input type="submit" value="Modify Pledge" /></form></div>
        {% elif supported %}
            <div class="btn_support"><form action="{% url 'pledge' work_id %}" method="get"><input type="submit" value="Add Support" /></form></div>
        {% else %}
            <div class="btn_support"><form action="{% url 'pledge' work_id %}" method="get"><input type="submit" value="Support" /></form></div>
        {% endif %}
      {% elif work.last_campaign.type == 3 %}
        <div class="btn_support">
            <a href="{% url 'download' work_id %}{% if action == 'preview' %}?testmode=1{% endif %}" class="hijax"><span>Download</span></a>
        </div>
        <div style="text-align: center;">... and thank the creators!</div>
      {% elif license_is_active %}
            <div class="btn_support">
                <a href="{% url 'download_purchased' work_id %}" class="hijax"><span>Download</span></a>
            </div>
      {% elif borrowable %}
            <div class="btn_support"><form action="{% url 'borrow' work_id %}" method="get"><input type="submit" value="Borrow" /></form></div>
      {% else %}
            <div class="btn_support"><form action="{% url 'purchase' work_id %}" method="get"><input type="submit" value="{% if next_acq %}{% if on_hold %}On Hold{% else %}Reserve{% endif %}{% else %}Purchase{% endif %}" /></form></div>
      {% endif %}
    {% elif work.is_free %}
            <div class="btn_support">
                <a href="{% url 'download' work_id %}" class="hijax"><span>Download</span></a>
            </div>
    {% endif %}
</div>

```

**Pull request merged**
